[tool.ruff]
target-version = "py310"


[tool.mypy]
pretty = true
show_error_codes = true
ignore_missing_imports = true
allow_redefinition = true
packages = ["angionet"]


[tool.pytest.ini_options]
testpaths = ["tests"]