[tool.ruff]
select = ["E", "F", "W", "I"]
include = ["./angionet/*.py"]


[tool.mypy]
pretty = true
show_error_codes = true
ignore_missing_imports = true
allow_redefinition = true
packages = ["angionet"]


[tool.codespell]
skip = ["*.ipynb"]


[tool.pytest.ini_options]
testpaths = ["./tests/"]